language: python
python:
    - "3.6"
install:
    - tools/create_portable_pyls.py
    - pip install tox
script:
    - cd plugin; tox
matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - python: 3.6
          env: TOXENV=py36
